apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: k8s-external-secrets-crds
  annotations:
    github.com/project-slug: mattjmorrison-homelab/k8s-external-secrets-crds
spec:
  type: secret-sync-crds
  owner: mattjmorrison-homelab
  system: external-secrets
